### ISSUE TITLE
Idioma

### ISSUE THREAD

**Issue by danicotillas** [hacklabcbba/viomap#1]
El mapa es para ser usado en Bolivia.
Tiene que estar todo en español como estaba antes.

**Comment by 51114u9** [comment]
Esta todo traducido, el idioma toma del navegador y su idioma... la gente en bolivia descarga el navegador en español. 

Sería bueno añadir un screenshot + detalles de sistema operativo, navegador y version (firefox about:config -> locale), revisar el idioma.

Probado en Firefox +40 en GNU/Linux, Windows 7 y Mac OS 10.6, falta probar en Safari y falta IE. Por ultimo si no se quiere quitamos.

**Comment by jgenso** [comment]
debian, chrome Versión 41.0.2272.118 (64-bit), 
![Uploading Captura de pantalla de 2015-08-30 18:40:33.png…]()

Sale en ingles

@51114u9

**Comment by 51114u9** [comment]
@jgenso no se ve la imagen :-/. De todas formas podrias mostrarme que obtiene de ejecutar `navigator.language` en la consola? si esta en español debería salir es o es-AR. Ctrl+Shift+K en FF y Ctrl+Shift+J en Chromium.

Por cierto hay [un bug](https://code.google.com/p/chromium/issues/detail?id=101138) en Chromium. Que se indica por ahí:

_In Firefox, you can change your language preferences by going into about:preferences#content, and clicking 'Choose' under 'Languages'. In Chrome, there is a similar panel in the Settings, but it actually doesn't modify the navigator.language property, which is a known bug. You'll need to download and install a French version of Chrome if you want to test this way._

**Comment by jgenso** [comment]
esta en español tanto el navegador como el sistema operativo

El 30 de agosto de 2015, 19:33, Marco Antonio notifications@github.com
escribió:

> @jgenso https://github.com/jgenso no se ve la imagen :-/. De todas
> formas podrias mostrarme que obtiene de ejecutar navigator.language en la
> consola? si esta en español debería salir es o es-AR. Ctrl+Shift+K en FF y
> Ctrl+Shift+J en Chromium
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hacklabcbba/viomap/issues/1#issuecomment-136217162.

## 

*Juan Jose Olivera Rodriguez Genso Iniciativas Web +591.44505438 *

**Comment by 51114u9** [comment]
@jgenso @danicotillas al parecer era un problema de hacerlo local. Acá una versión online sin errores: http://51114u9.github.io/projects/viomap/. Continuo la subida del resto del código.

Fixed c89a30ae781b8b482b286ccd4de9ecb9b64f678a

**Comment by jgenso** [comment]
Sip tienes razon
