### ISSUE TITLE
Diferenciar departamentos

### ISSUE THREAD

**Issue by danicotillas** [hacklabcbba/viomap#10]
¿Es posible hacer que cada departamento esté de un color para que así se diferencien?

**Comment by 51114u9** [comment]
Si es posible, pero creo que sobrecargar con el dibujo de cada región será mucho. Los límites de las regiones son ríos y el dibujo es muy detallado así que en conexiones lentas a Internet cargará más lento. Hay que experimentar.

Creo que no es prioritario, podríamos ver antes de la issue #7 y con un preview.

**Comment by danicotillas** [comment]
Entonces no, era sólo una idea. Que se quede como está o tal vez que por defecto aparezca el mapa "Humanitarian" que parece más afín a la lógica gráfica.
Como entenderás me están pidiendo más cosas gráficas que de usabilidad, así que resolvamos primero los puntos y usabilidad y luego le damos a lo gráfico.

**Comment by 51114u9** [comment]
Solucionado en 3d9e68044b8ef81d3e7b390654a210d230c7ce36

Cambió el diseño del fondo predeterminado, ahora HOTOSM. 

Queda todavía vigente la issue hasta hacer una prueba de la delimitación de regiones

**Comment by danicotillas** [comment]
Queda cerrado entonces este.
