### ISSUE TITLE
URGENTE finalización VioMap

### ISSUE THREAD

**Issue by danicotillas** [hacklabcbba/viomap#12]
Hola @jgenso @rd-o !!! Les escribo a través de un issue porque @51114u9 está desaparecido y no estamos pudiendo acabar el mapa. Es bien urgente.
Ahora mismo hay que acabar de colocar los puntos del resto de categorías y hacer que el menú funcione. Posteriormente hacerlo responsive. Díganme ¿tiene forma de contactar a Marco? ¿Saben si le ha pasado algo?
Díganme si pueden echar una mano o mañana desde temprano.

Gracias!

**Comment by 51114u9** [comment]
Cerrado por dupllicado.
