### ISSUE TITLE
Crear menú

### ISSUE THREAD

**Issue by danicotillas** [hacklabcbba/viomap#13]
Hacer que el menú funcione y muestre los resultados previos para buscar la info de cada lugar que está mapeado.

**Comment by jgenso** [comment]
una explicadtia mi no entender

**Comment by danicotillas** [comment]
Mira el ejemplo de http://mapanica.net, así más o menos

**Comment by 51114u9** [comment]
Añadido con https://github.com/hacklabcbba/viomap/commit/d535909bfb14c3368c405f41ad900e169c4bc7a1 https://github.com/hacklabcbba/viomap/commit/9070d0c960902673d350a3cb21e5d167b419f51b
