### ISSUE TITLE
¿Cómo fue hecho?

### ISSUE THREAD

**Issue by danicotillas** [hacklabcbba/viomap#14]
Faltaría incluir en esa parte la licencia con la que cuenta el VioMap.
Ya puse un texto con enlace al GitHub. Corregir lo que crean pertinente.

**Comment by 51114u9** [comment]
> Faltaría incluir en esa parte la licencia con la que cuenta el VioMap.

No hay nada. En este botón pienso que debería andar así:
- En "Acerca de" en 1 o 2 párrafos contar que es no como esta que es un montón de texto
- En "Contribuir" y "Créditos" con esas opciones van bien

![openbeermap_-_2015-10-07_14 55 41](https://cloud.githubusercontent.com/assets/1282371/10347788/95e4e21e-6d03-11e5-88c9-457227e83461.png)
![openbeermap_-_2015-10-07_14 55 50](https://cloud.githubusercontent.com/assets/1282371/10347787/95c2e524-6d03-11e5-81fe-2d8336fd173b.png)
![openbeermap_-_2015-10-07_14 55 58](https://cloud.githubusercontent.com/assets/1282371/10347786/95be523e-6d03-11e5-8afa-cc5365363d48.png)

**Comment by 51114u9** [comment]
En a22a92335db7b6e6477ad2b028fb656de71940cb ya tiene añadido todo esto.
