### ISSUE TITLE
Incluir medición de visitas

### ISSUE THREAD

**Issue by danicotillas** [hacklabcbba/viomap#15]
¿Qué le metemos? Imagino que google analytics rompe un poco la lógica no?
Si se animan a instalar Piwik vamos, o tal vez otra que recomienden.

**Comment by 51114u9** [comment]
> Si se animan a instalar Piwik vamos, o tal vez otra que recomienden.

Yo añado y lo hago pero el tema de permisos está pendiente para el servidor base de datos y alojamiento. 

Piwik nos sirve bien, así añadirmos a varios sitios y vemos de recibir feedback que estamos perdiendo. Algunos lugares a añadir barriohacker, mapa, viomap, hacklabsite, pad, trayectorias.

**Comment by Cesarluis** [comment]
En el servidor de viomap o en el del hackLab?

El 7 de octubre de 2015, 15:03, Marco Antonio notifications@github.com
escribió:

> Si se animan a instalar Piwik vamos, o tal vez otra que recomienden.
> 
> Yo añado y lo hago pero el tema de permisos está pendiente para el
> servidor base de datos y alojamiento.
> 
> Piwik nos sirve bien, así añadirmos a varios sitios y vemos de recibir
> feedback que estamos perdiendo. Algunos lugares a añadir barriohacker,
> mapa, viomap, hacklabsite, pad, trayectorias.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hacklabcbba/viomap/issues/15#issuecomment-146295416.

## 

César Luis Aranda Lozada
Celular: 72298563
En las viñas del Señor hay de todo, menos uvas.

**Comment by 51114u9** [comment]
> En el servidor de viomap o en el del hackLab?

Buena pregunta. ¿Dónde debería ser lo correcto? Hay algún documento que explique cómo esta esto de los servidores, servicios, hosting? Se está haciendo inmanegable.

Viendo como servicio a futuro en el servidor del HackLab al final hay que añadir una url.

**Comment by Cesarluis** [comment]
http://piwik.barriohacker.net/ , les pasare las credenciales por correo
para que lo prueben

El 7 de octubre de 2015, 16:53, Marco Antonio notifications@github.com
escribió:

> En el servidor de viomap o en el del hackLab?
> 
> Buena pregunta. ¿Dónde debería ser lo correcto? Hay algún documento que
> explique cómo esta esto de los servidores, servicios, hosting? Se está
> haciendo inmanegable.
> 
> Viendo como servicio a futuro en el servidor del HackLab al final hay que
> añadir una url.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hacklabcbba/viomap/issues/15#issuecomment-146324666.

## 

César Luis Aranda Lozada
Celular: 72298563
En las viñas del Señor hay de todo, menos uvas.

**Comment by danicotillas** [comment]
Lo ideal es que ya vaya para todos, así lo dejamos cerrado y tenemos stats menos intrusivas que G Analytics. En Barrio Hacker nos iba haciendo falta ya, así como hacklabcbba.org

**Comment by danicotillas** [comment]
He visto que se ha incluido Piwik en el VioMap. Ahora, ¿cómos se usa? Entré a piwik.barriohacker.net pero no ví nada de viomap.
Podríamos ver un taller rápido el sábado.

**Comment by 51114u9** [comment]
Cerrado b64136a77ffd39ed171b77cac4f987ad4d7ec924
