### ISSUE TITLE
Incluir Disqus

### ISSUE THREAD

**Issue by danicotillas** [hacklabcbba/viomap#16]
Debajo de cada punto al final de cada ventana incluir Disqus con un mensaje previo que diga:
"Comentanos qué tal fue el trato que recibiste en esta institución o cualquier información que creas necesaria:"

Código Disqus para viomap.alianzalibressinviolencia.org en http://pad.barriohacker.net/public_pad/disqus_viomap

En caso de necesitar acceso a la cuenta de alianzalibressinviolencia pedirme por otro medio.

**Comment by 51114u9** [comment]
Cerrada. Al no tener una página por cada nodo será una confusión.
