### ISSUE TITLE
Descarga de datos

### ISSUE THREAD

**Issue by danicotillas** [hacklabcbba/viomap#17]
Hace falta incluir un botón que diga: "Descárgate la base de datos en EXCEL o .PDF"
Hoy lo presentamos en reunión y nos pidieron que esto sea posible ya que es muy importante.

**Comment by 51114u9** [comment]
En a22a92335db7b6e6477ad2b028fb656de71940cb hice el nuevo enlace de decarga.

Ahora esta descargando los archivos geojson, para los otros archivos es necesario obtener "El enlace público para ése formato" haciendo File -> Publish y obtener el enlace.

No lo ví pero creo que sólo puede hacerlo el dueño.

**Comment by danicotillas** [comment]
Explícame cómo se hace eso porque no sé y necesitamos que esté para descarga hoy.

**Comment by 51114u9** [comment]
> Explícame cómo se hace eso porque no sé y necesitamos que esté para descarga hoy.

Lo hice, no era necesario ser dueño. Ya esta online. 

Hay que trabajar en qué significan "pintado amarilla" y los colores de las etiquetas... sino quitar. Si se puede cambiar el nombre a uno que indique lo que es "Mapa Genero no dice nada". En una última pestaña se podría añadir algún texto de cómo se hizo para obtener y qué hace falta. Así saldrá en el PDF.

Cerrado a2a538bdd4a1d911c8eeab9f10f603904780920d

**Comment by danicotillas** [comment]
Entonces, ¿lo que descarga es el spreadsheet que trabajamos en conjunto?
¿Se puede crear uno que no tenga todas esas columnas de lat, lng, color, etc... que no les servirán de mucho a las organizaciones?
Explícame cuál crees que es la mejor manera porfa y lo hacemos de una!

**Comment by 51114u9** [comment]
Si por eso era de poner un nombre. Y si ocultas las columnas? No perdemos nada ni ellos se enteran

**Comment by danicotillas** [comment]
Hecho!

_Daniel Cotillas Ruiz__OpenPGP Key
https://pgp.mit.edu/pks/lookup?op=get&search=0x1A78FC0E_
_Twitter *_@danicotillas\* https://www.twitter.com/danicotillas
_Barrio Hacker GNUsocial http://charlemos.barriohacker.net/danicotillas_

2015-10-11 15:29 GMT-04:00 Marco Antonio notifications@github.com:

**Comment by 51114u9** [comment]
Quedó genial en pdf. Ya está en vivo.
