### ISSUE TITLE
Buscador

### ISSUE THREAD

**Issue by danicotillas** [hacklabcbba/viomap#18]
Aún no funciona adecuadamente y es muy importante.
Me han pedido que hasta el **viernes** esté todo porfa, es decir, mañana. ¿Se podrá?

**Comment by danicotillas** [comment]
Comento aquí que sigue sin funcionar bien. Sincronicé todos tus cambios, los subí y se ha desconfigurado el CSS. Mira a ver qué pasó porfa.

**Comment by 51114u9** [comment]
> Comento aquí que sigue sin funcionar bien. Sincronicé todos tus cambios, los subí y se ha desconfigurado el CSS. Mira a ver qué pasó porfa.

En la tarde-noche revisaré el buscador y esas fallas.

**Comment by 51114u9** [comment]
Solucionado en 44db1d5dfeffd56d2c9eb8041aaa499ce4f035fb
