### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by danicotillas** [hacklabcbba/viomap#19]
Acabo de actualizar y se rompió el CSS. Por favor, alguien que pueda ver cómo solucionarlo para que mañana esté ok.

**Comment by 51114u9** [comment]
Bueno la idea era revisar un poco antes de poner en funcionamiento esta versión...

Revisado y esta todo bien, debe ser tu navegador. En Chrome usan mucho la caché, por ahí estas viendo una fusión entre antiguo y nuevo. CTRL+F5 siempre.
