### ISSUE TITLE
Cluster puntos

### ISSUE THREAD

**Issue by danicotillas** [hacklabcbba/viomap#2]
Generar clusters (creo que me estoy refieriendo bien, corríjanme las dudas) como en la primera imagen para que no aparezca como en la segunda:

![captura de pantalla 2015-08-31 12 28 21](https://cloud.githubusercontent.com/assets/7635775/9588082/2ef76ada-4ff4-11e5-9b28-d8f606d56894.png)

![captura de pantalla 2015-08-31 15 21 30](https://cloud.githubusercontent.com/assets/7635775/9588086/32418482-4ff4-11e5-823a-0f18e3a6c9dd.png)

**Comment by 51114u9** [comment]
Solucionado en 3d9e68044b8ef81d3e7b390654a210d230c7ce36.

Sólo se implementó para la 1ra categoría (slims), es repetible a las otras una vez esté probado el diseño definitivo.
