### ISSUE TITLE
ToolTip en menú categorías

### ISSUE THREAD

**Issue by danicotillas** [hacklabcbba/viomap#3]
Mostrar el menú de categorías como en ejemplo que me enviaste. Hay que añadir al nombre además una descripción de lo que es cada categoría:

![captura de pantalla 2015-08-31 15 24 49](https://cloud.githubusercontent.com/assets/7635775/9588114/68e48b2e-4ff4-11e5-9037-1fc7168de41a.png)

**Comment by 51114u9** [comment]
@danicotillas Duda: ¿está bien el diseño de las categorías o hay que cambiar? 

La descripción está bien hacerla como `tooltip`. Ejemplo [clic aquí](http://getbootstrap.com/javascript/#tooltips) 

![sss](https://cloud.githubusercontent.com/assets/1282371/9624436/e022ef7e-511a-11e5-93bb-7e7ba9c95c5f.png)

**Comment by danicotillas** [comment]
El diseño está bueno. No sé si @jgenso ya aplicó algún cambio que me habló.
Lo del tooltip me parece perfecto! Espero luego no me digan que no...

**Comment by danicotillas** [comment]
Actualizo desde este issue algunos puntos importantes, a ser posible tenerlo de urgencia:
- Que el menú de las categorías incluya checkbox para que se "entienda" que hay que pinchar para seleccionar.
- Colocar todo en español.
- Colocar los tooltips en el menú de categorías con la descripción de cada institución.
- Añadir la columna "info" en cada globo de info con la descripción de la institución (lo voy a añadir en el excel).
- Lograr que funcione el buscador.

Estos 4 puntos me solicitan que pueda estar para mostrar el fin de semana. Gracias!

**Comment by 51114u9** [comment]
Añadido con https://github.com/hacklabcbba/viomap/commit/4f1b560a9c630f44647502764570c47d700707ea https://github.com/hacklabcbba/viomap/commit/63e3a86bf25fe62443da097d43e94e1dd27098d9
