### ISSUE TITLE
Información de cada punto

### ISSUE THREAD

**Issue by danicotillas** [hacklabcbba/viomap#4]
Colocarlo en español (puede ser este tema de los navegadores) y además incluir:

· Departamento
· Municipio

![captura de pantalla 2015-08-31 15 26 13](https://cloud.githubusercontent.com/assets/7635775/9588145/9966ade0-4ff4-11e5-8fe9-8943131fd152.png)

**Comment by 51114u9** [comment]
@danicotillas "inteligentemente" yo fusioné estos dos datos en la dirección, según formato `<dirección>, <municipio>, <departamento>`. 

¿Con esta issue separamos en tres filas? + añadiendo el resto de campos según cada tipo.

|  Dirección          |  Avenida Circunvalación Nro 275  |
|  Municipio          |  Arani                                            |
|  Departamento  |  Cochabamba                               |

Por fa, separar issue. El buscador debería ser otra issue con alguna explicación corta de lo importante.

**Comment by danicotillas** [comment]
Si, exactamente. Que quede así.

Me parece lo del buscador, me avisas cuando marche.

**Comment by 51114u9** [comment]
Solucionado en 3d9e68044b8ef81d3e7b390654a210d230c7ce36

La traducción es general, se hará en  base a los datos.
