### ISSUE TITLE
Incluir logo ALSV en menu

### ISSUE THREAD

**Issue by danicotillas** [hacklabcbba/viomap#6]
Incluir este logo en el menú. Tal vez se puede poner un footer donde vaya el logo y no quede tan ruidoso arriba, como vean.

El logo lo he subido al GitHub.

![captura-de-pantalla-2015-08-31-15 31 30](https://cloud.githubusercontent.com/assets/7635775/9588363/d063c0e8-4ff5-11e5-8c34-a56eb88b0399.png)

**Comment by 51114u9** [comment]
Mi solución:
- llevar el logotipo aslv a la derecha
- llevar iniciativay compatir a iconos en la zona inferior derecha (ver [ejemplo](http://danielmontague.com/projects/easyButton.js/v1/examples/))
- dar acción al ícono propuesto arriba como `popup` con tabs (ver [ejemplo](http://getbootstrap.com/javascript/#tabs))
- dar enlace al logotipo hacia la página web.

Necesario diseñar cómo se verá en responsivo (600 pixeles de ancho para abajo)... creo que icono VIOMAP se vuelve `el ojito` y el nuevo `alsv`se vuelve uno con solo los perfiles de cabezas.

**Comment by danicotillas** [comment]
Para no seguir abriendo issues mencionar que en el menú la tipografía a usarse en el subtítulo sea "Arial" porque me dicen que tienen problemas ya que se ve borroso... imagino que es por ser Helvética.

**Comment by 51114u9** [comment]
Añadido con a0c7540a99bfdbb51fafc56488a4640d9b169ad0 y 5d19869a0f75d0eaa4c738cca15f4e9e73720407
