### ISSUE TITLE
Reporte de error lugar/datos

### ISSUE THREAD

**Issue by danicotillas** [hacklabcbba/viomap#7]
Me he dado cuenta que subir la dirección de los puntos es bastante complicada, sobre todo por las indicaciones de la dirección.
Lo mejor sería crear un botón dentro de "Iniciativa" que diga "Ayúdanos a mejorar el mapa":

Si has notado que alguna información está incorrecta por favor escríbenos diciéndonos qué información debemos corregir.

Aquí se puede hacer tipo formulario o colocar simplemente "Escríbenos a hacklab@martadero.org explicándonos qué información corregir". Como crean que funcione mejor teniendo en cuenta que no sabemos en qué servidor estará y no podremos configurar el envío de emails.

**Comment by 51114u9** [comment]
@danicotillas mirá como hicieron en http://arbolesciudad.com.ar/, algo similar y sencillo se podría ser. No es directo que añade el punto sino hay un filtro que avisa que hay nueva info.

> Si has notado que alguna información está incorrecta por favor escríbenos diciéndonos qué información debemos corregir. No sé guarda nada pero avisa internamente 

Del lugar donde apunta el icono, hay un desplzamiento general, veré de hacerlo automático el movido. Iré marcando en el documento los errores.

El problema está en la dirección, cuando es exacta no hay problema (Av. X entre Y Nro. 345) pero cuando por referencia es un carnaval de colores. En el documento propongo para que sea más entendible y sencillo.

**Comment by danicotillas** [comment]
Perfecto! Me encanta ese "Reporte de error".
Si se puede instalar maravilla. Ahora, ¿qué crees que sea lo mejor? Que el reporte llegue a hacklab@martadero.org y de ahí yo lo derivo o se puede hacer que llegue aquí al GitHub para que estemos todos informados al tiro?

**Comment by 51114u9** [comment]
@danicotillas 

> Si se puede instalar maravilla. Ahora, ¿qué crees que sea lo mejor? Que el reporte llegue a hacklab@martadero.org y de ahí yo lo derivo o se puede hacer que llegue aquí al GitHub para que estemos todos informados al tiro?

Hay que probar que pueda llegar a un drive de google, pero es incógnita. Hay que investigar. Creo que es prioridad baja, veámoslo al final.

**Comment by danicotillas** [comment]
Ok, me parece.

**Comment by danicotillas** [comment]
Como vimos ayer tal vez lo mejor sea incluirlo como un enlace desde cada ventana que diga:

"Si encuentras omisiones y/o errores en los datos o la ubicación de las oficinas ayúdanos reportando este problema AQUÍ"

Además, pondría al lado de "Descargar" en el menú de arriba otro que diga "Sugerencias/Reportes" que lleve al formulario.

**Comment by 51114u9** [comment]
En a22a92335db7b6e6477ad2b028fb656de71940cb ya esta preparado la nueva estructura para añadir esta opción.

Hay un formulario que se incluirá en la carpeta compartida VIOMAP, es necesario un poco de ayuda para mejorarlo y hacerlo amigable con el texto.

**Comment by 51114u9** [comment]
Añadido y online con el commit e88f821e3bd189033464e1c3a618b4f2a123fabe.

Existen tres formas de ingresar: a) por la opción "Acerca de"-> "Contribuir", b) botón explícito, c) popup del punto.
