### ISSUE TITLE
Incluir definiciones de las categorías

### ISSUE THREAD

**Issue by danicotillas** [hacklabcbba/viomap#9]
Veamos la mejor forma de que aparezca, si en el mismo menú o en cada uno de los popups (Tal vez en ambas ya que es una información importante para mostrar en cada popup):

**Fuerza Especial de Lucha Contra la Violencia (FELCV)**
La FELCV tiene la obligación de recibir tu denuncia en caso de violencia hacia las mujeres ya  que es la división especializada de la Policía Boliviana encargada de la prevención, auxilio e investigación, identificación y aprehensión de los presuntos responsables de hechos de violencia hacia las mujeres,  bajo la dirección funcional del Ministerio Público.

**Fuerza Especial de Lucha Contra el Crimen (FELCC)**
La FELCC tiene la obligación de recibir tu denuncia cuando una persona desaparece o sospechas que puede ser víctima de trata de personas. Es la división especializada de la Policía Boliviana encargada de la prevención e identificación de delitos, investigación y aprehensión de los presuntos responsables, búsqueda, recolección y custodia de evidencias, el estudio, análisis técnico y científico de las pruebas materiales y evacuación de dictámenes periciales.  
También debe recibir tu denuncia en casos de violencia hacia las mujeres cuando en tu municipio no hay FELCV.

**Servicio Legal Integral Municipal (SLIM)**
Es un servicio público municipal permanente y gratuito para la protección y defensa psicológica, social y legal de las mujeres en situación de violencia, para garantizar la vigencia y ejercicio pleno de sus derechos. 
Debe asesorarte y acompañarte a hacer tu denuncia en la Policía o en el Ministerio Público

**Ministerio Público (Fiscalía del Estado)**
Tiene la finalidad de defender la legalidad y los intereses generales de la sociedad, ejercer la acción penal pública e interponer otras acciones, en el marco establecido por la Constitución Política del Estado, los Tratados y Convenios Internacionales en materia de Derechos Humanos y las leyes.

**Fiscalía Especializada en Atención a Víctimas de Atención Prioritaria (FEVAP)**
Es una instancia dependiente del Ministerio Público creada con el objetivo de ejercer persecución penal especializada de hechos por delitos previstos en la Ley No 263, “Ley Integral  contra  la Trata y Tráfico de Personas”, y la Ley No 348, “Ley Integral  para Garantizar a las Mujeres una Vida Libre de Violencia”. Considera victimas de atención prioritaria a todas aquellas personas, especialmente mujeres, niños, niñas y adolescentes, que por su situación de vulnerabilidad requieren atención preferencial  y medidas de protección inmediata.

**Instituto de Investigación Forense (IDIF)**
Es una instancia, dependiente del Ministerio Público, encargada de realizar los estudios  científicos-técnicos y laboratorios requeridos para la investigación de los delitos.

**Comment by 51114u9** [comment]
Esto podría ser añadido en un botón cerca de los controles de zoom (inferior derecha). Icono [?] http://danielmontague.com/projects/easyButton.js/v1/examples/. Y que llame a un `popup`.

**Comment by danicotillas** [comment]
Creo que es mejor que se muestre como popup desde el menú de categorías o que aparezca en la descripción del popup de cada punto. Veamos.

**Comment by danicotillas** [comment]
Agrego en este issue cómo deberían de verse las categorías a la izquierda (además del popup con las definiciones de arriba):
- SLIMs
- FELCV
- FELCC (Dentro de ésta se agregan las Divisiones de Trata y Tráfico)
- Ministerio Público
  - FEVAPs
  - IDIF
- Órgano Judicial
  - Tribunales Supremos y Departamentales de Justicia
  - Distritos Judiciales
  - Juzgados y/o Tribunales especializados

Voy a actualizar los iconos aquí: https://docs.google.com/document/d/1gCHSBtUm0G4XHNsBAHdeaCpNWvSY0-1M0sSaOQEzq1A/edit?usp=sharing

**Comment by 51114u9** [comment]
cerrado, es redundante, ya existe en cada punto.
